language: node_js
node_js:
- '5'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - NODE_ENV=production CXX=g++-4.8
branches:
  only:
  - develop
install: npm install
script: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_381afb105c0d_key -iv $encrypted_381afb105c0d_iv -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
- eval `ssh-agent -s`
- ssh-add deploy_key
- git config --global user.name "Travis CI"
- git config --global user.email "opensource@skbkontur.ru"
deploy:
  provider: script
  script: npm run publish
  skip_cleanup: true
  on:
    branch: develop
