language: node_js
node_js:
- '5'
branches:
  only:
  - develop
install: npm install --only=dev
script: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_381afb105c0d_key -iv $encrypted_381afb105c0d_iv -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
- eval `ssh-agent -s`
- ssh-add deploy_key
- git config user.name "Travis CI"
- git config user.email "$COMMIT_AUTHOR_EMAIL"
deploy:
  provider: script
  script: npm run publish
  skip_cleanup: true
